### ISSUE TITLE
sass converter emits normalize.css and can't be disabled

### ISSUE THREAD

**Issue by kotet** [kotet/ultralight#3]
```css
/*! normalize.css v4.1.1 | MIT License | github.com/necolas/normalize.css */
/**
 * 1. Change the default font family in all browsers (opinionated).
 * 2. Prevent adjustments of font size after orientation changes in IE and iOS.
 */
html {
  font-family: sans-serif;
  /* 1 */
  -ms-text-size-adjust: 100%;
  /* 2 */
  -webkit-text-size-adjust: 100%;
  /* 2 */
}
...
```

```console
$ ls -lh _site/assets/css/
total 76K
-rw-r--r-- 1 vscode vscode 75K Sep 22 06:21 style.css
```
